version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/github_action
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: /opt/codedeploy-agent/deployment-root/7b3f3332-bf13-4dca-ace5-26aa3dad8505/d-AMO6LAYMI/deployment-archive/scripts/gh_deploy.sh
      timeout: 60
      runas: root
