spring:
  datasource:
    url: jdbc:mysql://localhost:3307/parking-people?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    #driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug #info
    org.hibernate.type: trace