spring:
  datasource:
    url: jdbc:mariadb://parking-people-db.czyhbytkkx2n.ap-northeast-2.rds.amazonaws.com:3306/parking_people
    username:
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none #create #update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
    show-sql: false # dev에서 true
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect #이거 자동이라고 들은거 같은데, 나중에 확인해보기

#  profiles:
#    include: API-KEY

logging:
  level:
    org.hibernate.SQL: info #debug
    org.hibernate.type.BasicTypeRegistry: WARN # org.hibernate.type: trace


override:
    value : 'from application.yml'

tmap-key:
