spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/parking
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

  profiles:
    include: API-KEY

logging:
  level:
    org.hibernate.SQL: debug #info
    org.hibernate.type: trace