spring:
  datasource:
    url: jdbc:mysql://localhost:3307/parking-people?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    #driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update #create #update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect #이거 자동이라고 들은거 같은데, 나중에 확인해보기

  profiles:
    include: API-KEY

logging:
  level:
    org.hibernate.SQL: debug #info
    org.hibernate.type: trace
